# Generated by Django 5.2.1 on 2025-09-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Aeropress', 'aeropress'), ('Drip Coffee', 'drip coffee'), ('V60', 'v60')], default='aeropress')),
                ('coffee_grams', models.FloatField(default=1)),
                ('water_grams', models.FloatField(default=1)),
                ('rating', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='0')),
                ('tasting_notes', models.TextField()),
            ],
        ),
    ]
