# Generated by Django 5.2.1 on 2025-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_brew_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='method',
            field=models.CharField(choices=[('aeropress', 'Aeropress'), ('drip coffee', 'Drip Coffee'), ('v60', 'V60')], default='aeropress'),
        ),
    ]
