# Generated by Django 5.2.1 on 2025-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_brew_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='method',
            field=models.CharField(choices=[('aeropress', 'Aeropress'), ('drip_coffee', 'Drip Coffee'), ('v60', 'V60')], default='aeropress'),
        ),
    ]
